-- D008からD026までのテーブル設定を一括INSERT
INSERT INTO `cdp_config.table_mapping` (
  table_id,
  table_name,
  load_type,
  write_disposition,
  skip_leading_rows,
  field_delimiter,
  allow_quoted_newlines,
  allow_jagged_rows,
  max_bad_records,
  gcs_inbox_path,
  primary_key,
  update_column,
  frequency,
  description,
  created_at,
  updated_at
) VALUES
  ('D008', 'l0_D008_format_type', 'full', 'WRITE_APPEND', 0, ',', true, false, 0, 'tokai-cdp-production-project-cdp-data/raw/D008_format_type/inbox', NULL, NULL, 'daily', 'フォーマットタイプマスタ', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
  ('D009', 'l0_D009_attribute_type', 'full', 'WRITE_APPEND', 0, ',', true, false, 0, 'tokai-cdp-production-project-cdp-data/raw/D009_attribute_type/inbox', NULL, NULL, 'daily', '属性タイプマスタ', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
  ('D010', 'l0_D010_marital_status', 'full', 'WRITE_APPEND', 0, ',', true, false, 0, 'tokai-cdp-production-project-cdp-data/raw/D010_marital_status/inbox', NULL, NULL, 'daily', '婚姻ステータスマスタ', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
  ('D011', 'l0_D011_spatial_division', 'full', 'WRITE_APPEND', 0, ',', true, false, 0, 'tokai-cdp-production-project-cdp-data/raw/D011_spatial_division/inbox', NULL, NULL, 'daily', '空間区分マスタ', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
  ('D012', 'l0_D012_consignment_fee_flag', 'full', 'WRITE_APPEND', 0, ',', true, false, 0, 'tokai-cdp-production-project-cdp-data/raw/D012_consignment_fee_flag/inbox', NULL, NULL, 'daily', '委託料金フラグマスタ', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
  ('D013', 'l0_D013_office_master', 'full', 'WRITE_APPEND', 0, ',', true, false, 0, 'tokai-cdp-production-project-cdp-data/raw/D013_office_master/inbox', NULL, NULL, 'daily', '事業所マスタ', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
  ('D014', 'l0_D014_dealer_master', 'full', 'WRITE_APPEND', 0, ',', true, false, 0, 'tokai-cdp-production-project-cdp-data/raw/D014_dealer_master/inbox', NULL, NULL, 'daily', '販売店マスタ', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
  ('D015', 'l0_D015_customer_history', 'full', 'WRITE_APPEND', 0, ',', true, false, 0, 'tokai-cdp-production-project-cdp-data/raw/D015_customer_history/inbox', NULL, NULL, 'daily', '顧客履歴', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
  ('D016', 'l0_D016_customer_detail', 'full', 'WRITE_APPEND', 0, ',', true, false, 0, 'tokai-cdp-production-project-cdp-data/raw/D016_customer_detail/inbox', NULL, NULL, 'daily', '顧客詳細', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
  ('D017', 'l0_D017_Equipment_Maintenance', 'full', 'WRITE_APPEND', 0, ',', true, false, 0, 'tokai-cdp-production-project-cdp-data/raw/D017_Equipment_Maintenance/inbox', NULL, NULL, 'daily', '機器メンテナンス', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
  ('D018', 'l0_D018_purchase_detail', 'full', 'WRITE_APPEND', 0, ',', true, false, 0, 'tokai-cdp-production-project-cdp-data/raw/D018_purchase_detail/inbox', NULL, NULL, 'daily', '購入詳細', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
  ('D019', 'l0_D019_reception_info', 'full', 'WRITE_APPEND', 0, ',', true, false, 0, 'tokai-cdp-production-project-cdp-data/raw/D019_reception_info/inbox', NULL, NULL, 'daily', '受付情報', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
  ('D020', 'l0_D020_tanpopo_price_history', 'full', 'WRITE_APPEND', 0, ',', true, false, 0, 'tokai-cdp-production-project-cdp-data/raw/D020_tanpopo_price_history/inbox', NULL, NULL, 'daily', 'たんぽぽ料金履歴', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
  ('D021', 'l0_D021_tanpopo_landlord_info', 'full', 'WRITE_APPEND', 0, ',', true, false, 0, 'tokai-cdp-production-project-cdp-data/raw/D021_tanpopo_landlord_info/inbox', NULL, NULL, 'daily', 'たんぽぽ家主情報', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
  ('D022', 'l0_D022_tanpopo_safety_service_report', 'full', 'WRITE_APPEND', 0, ',', true, false, 0, 'tokai-cdp-production-project-cdp-data/raw/D022_tanpopo_safety_service_report/inbox', NULL, NULL, 'daily', 'たんぽぽ安全サービスレポート', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
  ('D023', 'l0_D023_tanpopo_event_reservation', 'full', 'WRITE_APPEND', 0, ',', true, false, 0, 'tokai-cdp-production-project-cdp-data/raw/D023_tanpopo_event_reservation/inbox', NULL, NULL, 'daily', 'たんぽぽイベント予約', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
  ('D024', 'l0_D024_tanpopo_mypage_member_info', 'full', 'WRITE_APPEND', 0, ',', true, false, 0, 'tokai-cdp-production-project-cdp-data/raw/D024_tanpopo_mypage_member_info/inbox', NULL, NULL, 'daily', 'たんぽぽマイページ会員情報', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
  ('D025', 'l0_D025_tanpopo_sales_history', 'full', 'WRITE_APPEND', 0, ',', true, false, 0, 'tokai-cdp-production-project-cdp-data/raw/D025_tanpopo_sales_history/inbox', NULL, NULL, 'daily', 'たんぽぽ売上履歴', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
  ('D026', 'l0_D026_lpgas_mypage_target', 'full', 'WRITE_APPEND', 0, ',', true, false, 0, 'tokai-cdp-production-project-cdp-data/raw/D026_lpgas_mypage_target/inbox', NULL, NULL, 'daily', 'LPガスマイページ対象', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());